### ISSUE TITLE
Issue with GBoard

### ISSUE THREAD

**Issue by xerta555** [Magisk-Modules-Alt-Repo/data_isolation_support#1]
Hi

First, your module works for it's main goal, so good works.

But i get an issue after the restart: i cannot longer use the gesture input of GBoard on my device.

Idk which logfile we need to investiguate that, if something could help you, tell me.

Thanks.

**Comment by HuskyDG** [comment]
What is your Android version?

**Comment by xerta555** [comment]
> What is your Android version?

Android 10
Stock OnePlus ROM.
Need other infos ?

**Comment by HuskyDG** [comment]
You can modify `dynmount.sh` and add these line inside `prepareEnterMntNs` function to make script ignore isolated data folder for GBoard: 

```
if [ "$PROC" == "process name of gboard" ]
    exit 1
fi

**Comment by xerta555** [comment]
> You can modify `dynmount.sh` and add these line inside `prepareEnterMntNs` function to make script ignore isolated data folder for GBoard:
> 
> ```
> if [ "$PROC" == "process name of gboard" ]; then
>     exit 1
> fi
> ```

I confirm that it works successfully now 👍🏻 
Maybe that you should add a little note in your Readme related to exclusions if other users would like to make exclusions or getting issue(s)

**Comment by xerta555** [comment]
I note that when i restart my device, a the following page: https://support.google.com/messages/answer/9744268?visit_id=638059984148202660-4032840790&p=bhm&rd=1 is opened at the startup.

I assume it's due to the module as this link never opened itself before.
I'm not sure of which app(s) don't work propeply.

Maybe that we need a logfile for that ?

EDIT: I note also that the Play Store app is auto-disconnected from the Google account, and it's no longer possible to access to Play Store. Even if i add an if for the PS in the shell file, it won't works.
I think that the PS app try to read informations of other system apps, but theses infos aren't visible.
For now, i have disabled the two Magisk modules and rebooted my device to be able to access the Play Store again.

**Comment by HuskyDG** [comment]
@xerta555 can you test this?

[app_data_isolation.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10201498/app_data_isolation.zip)

**Comment by xerta555** [comment]
> @xerta555 can you test this?
> 
> [app_data_isolation.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10201498/app_data_isolation.zip)

Tested: same issue with the Play Store app.
Additionaly: each app i try to open make arround 2-3 more seconds to open up.
There is my Magisk log: [magisk_log_2022-12-11T14.33.51.log](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10202314/magisk_log_2022-12-11T14.33.51.log)

If u need other logfile(s), tell me.

**Comment by kokoromagic** [comment]
> > @xerta555 can you test this?
> > [app_data_isolation.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10201498/app_data_isolation.zip)
> 
> Tested: same issue with the Play Store app. Additionaly: each app i try to open make arround 2-3 more seconds to open up. There is my Magisk log: [magisk_log_2022-12-11T14.33.51.log](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10202314/magisk_log_2022-12-11T14.33.51.log)
> 
> If u need other logfile(s), tell me.

Can you send `/data/system/packages.list` ?

**Comment by xerta555** [comment]
> Can you send /data/system/packages.list ?

Of course: [packages.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10202325/packages.zip)
(Just extract it).

Edit: i forget to enable again the module

EDIT 2: Ok there is my file with the module enabled (sorry for the mistake): [packages.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10202338/packages.zip)

**Comment by HuskyDG** [comment]
[app_data_isolation.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10218502/app_data_isolation.zip)

**Comment by xerta555** [comment]
> [app_data_isolation.zip](https://github.com/Magisk-Modules-Alt-Repo/data_isolation_support/files/10218502/app_data_isolation.zip)

I have test it and apparently it now works successfully
PS can be opened normally
All other apps open normally without lags
Google Keyboard exclusion works like before
All su detector apps detect nothing

I'm going to test it on the long time to check if everything is ok and will come back here if i get an issue.

Good works 👍🏻

**Comment by xerta555** [comment]
If i can purpose an inprovement: i think that it would be nice if you add a simple way to add an app in exclusion list for users which aren't familiar with the shell.
